# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/jekyll
image: ruby:2.3

pages:
  stage: deploy
  script:
  - gem install jekyll
  - jekyll build -d public
  - gem build editorial_jekyll_theme.gemspec
  artifacts:
    paths:
    - public
    - [*].gem
  only:
  - master