image: ruby:2.3

editorial_jekyll_theme:
  stage: build
  script:
  - gem install jekyll
  - jekyll build -d public
  - gem build editorial_jekyll_theme.gemspec
  artifacts:
    paths:
    - public
    - "editorial_jekyll_theme-*.gem"
  only:
  - master